model:
  name: vit
  task_type: reg

data:
  file_path: "${TRAIN_DIR}/dataset.h5"
  val_path:  "${VAL_DIR}/dataset.h5"
  test_path: "${TEST_DIR}/dataset.h5"
  cov_path: "${PCA_DIR}/cov.pt"
  allow_compute: false
  num_samples: 100000
  num_test_samples: 1000
  param: T_eff
  label_norm: 'minmax' # 'standard', 'minmax', 'zscore', or 'none'

noise:
  noise_level: 0

# python3 scripts/fit_preprocessor.py --config "$CONFIG_DIR/zca.yaml"  --mode zca --output "$PCA_DIR/zca.pt"