model:
  name: vit
  image_size: 4096    
  patch_size: 100
  hidden_size: 128
  num_hidden_layers: 6
  num_attention_heads: 8
  num_labels: 2    
  stride_ratio: 1
  proj_fn: 'SW'

train:
  batch_size: 128
  ep: 100
  debug: 0
  workers: 24

loss: 
  name: 'T1'

opt:
  type: 'adam'
  lr: 0.001
  lr_sch: plateau
  factor: 0.8
  patience: 2

data:
  file_path: '/datascope/subaru/user/swei20/data/bosz50000/test/mag215/train_100k/dataset.h5'
  val_path: '/datascope/subaru/user/swei20/data/bosz50000/mag215/train_1k/dataset.h5'
  test_path: '/datascope/subaru/user/swei20/data/bosz50000/mag215/val_1k/dataset.h5'
  num_samples: 100000
  num_test_samples: 1000
  param_idx: 1  

mask:
  mask_ratio: 0.85

noise:
  noise_level: 0

project: 'vit-test'