program: scripts/sweep.py
method: grid
metric:
  name: val_mae
  goal: minimize
parameters:
  vit_config:
    value: configs/anyon/test.yaml
  warmup.UV:
    values: [V, Vt, U, Ut]
  model.proj_fn:
    values: [SW, C1D]
  # Examples of other easy knobs to add:
  # warmup.r:
  #   values: [0, 32, 64, 128]
  # train.lr:
  #   values: [0.001, 0.0005]
