program: scripts/sweep.py
method: grid
metric:
  name: val_mae
  goal: minimize
parameters:
  r:
    values: [8, 16, 32, 64, 128]
  vit_config:
    value: configs/vit.yaml
  # You can override other config keys via sweep parameters if needed, e.g.:
  # train.lr:
  #   values: [1e-3, 5e-4]
