program: scripts/sweep.py
method: grid
metric:
  name: val_mae
  goal: minimize
parameters:
  warmup.shrinkage:
    values: [0.0, 0.1]
  warmup.r:
    values: [2]
  warmup.freeze_epochs:
    values: [2]
  vit_config:
    value: "configs/vit.yaml"
