_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": num_params(M)
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": lr
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": l1_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_l1_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_mae
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_r2
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_mae
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": l1_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_l1_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_r2
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 106
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 106
            "3":
                - 7
                - 13
                - 16
                - 55
                - 66
            "4": 3.13.1
            "5": 0.20.1
            "6": 4.52.4
            "12": 0.20.1
            "13": linux-x86_64
config:
    value:
        data:
            file_path: ./data/test_1k/dataset.h5
            label_norm: minmax
            num_samples: 100000
            num_test_samples: 1000
            param: T_eff, log_g, M_H
            test_path: ./data/test_1k/dataset.h5
            val_path: ./data/val_1k/dataset.h5
        loss:
            name: l1
        mask:
            mask_ratio: 0.85
        model:
            hidden_size: 128
            image_size: 4096
            name: vit
            num_attention_heads: 1
            num_hidden_layers: 2
            num_labels: 3
            patch_size: 128
            proj_fn: SW
            stride_size: 32
            task_type: reg
        noise:
            noise_level: 0
        opt:
            factor: 0.8
            lr: 0.001
            lr_sch: plateau
            patience: 2
            type: adam
        project: vit-test
        train:
            batch_size: 128
            debug: 0
            ep: 500
            gpus: 1
            save: true
            workers: 10
        warmup:
            embed: false
            global: false
data:
    value:
        file_path: ./data/test_1k/dataset.h5
        label_norm: minmax
        num_samples: 100000
        num_test_samples: 1000
        param: T_eff, log_g, M_H
        test_path: ./data/test_1k/dataset.h5
        val_path: ./data/test_1k/dataset.h5
loss:
    value:
        name: l1
mask:
    value:
        mask_ratio: 0.85
model:
    value:
        hidden_size: 128
        image_size: 4096
        name: vit
        num_attention_heads: 1
        num_hidden_layers: 2
        num_labels: 3
        patch_size: 128
        proj_fn: SW
        stride_size: 32
        task_type: reg
noise:
    value:
        noise_level: 0
opt:
    value:
        factor: 0.8
        lr: 0.001
        lr_sch: plateau
        patience: 2
        type: adam
project:
    value: vit-test
train:
    value:
        batch_size: 128
        debug: 0
        ep: 500
        gpus: 1
        save: true
        workers: 10
warmup:
    value:
        embed: false
        global: false
